### ISSUE TITLE
Clean up old unused images on the server

### ISSUE THREAD

**Issue by daniel-j-h** [usedgoodreads/usedgoodreads#24]
At the moment we just push images to the server, but we never clean them up.

I just ran

    docker system prune -a --volumes

and cleaned up roughly 3 GB of images.

We should look into how to clean up old unused images.

Maybe we then can have a cron job on the server (or Travis?) clean up for us on a regular basis.

**Comment by ucyo** [comment]
Maybe erase all images except the latest and next to latest one? Rather than have a separate script, we could execute it right before the image is pushed to the machine (e.g. [here](https://github.com/usedgoodreads/usedgoodreads/blob/0313b83ae0a5777d768d7d161144dc683e67836c/.travis.yml#L45)). Just `prune` the images and push the image in the next step. Then we have the latest two images and a possible backup if something goes wrong.

**Comment by daniel-j-h** [comment]
Ah, yes that sounds like a good idea! :rocket:  We could also `docker tag` the last versions then on the remote host, e.g. as in `current` and `previous`.
