### ISSUE TITLE
Use ISBN as ground truth id

### ISSUE THREAD

**Issue by daniel-j-h** [usedgoodreads/usedgoodreads#5]
Can we use a book's ISBN as it's unique id we store and use for queries?

For example for the book

https://www.goodreads.com/book/show/36236132-growing-a-revolution

in the HTML's head there's

    <meta content='9780393356090' property='books:isbn'>

giving us the ISBN without ugly parsing and without having to use the Goodreads package.

Is the ISBN enough to search various 2nd hand apis?

**Comment by ucyo** [comment]
Well, it depends. `booklooker.de` provides no API, but the search URL is nicely defined and it allows searching via ISBN. Search via ISBN is also enabled for `amazon.de`. The other two providers `kleinanzeigen.ebay.de` and `rebuy.de` only have search via title and the URL request is ugly :(

But we get both information via the HTML header, since also the title is included in the HTML. No API call needed. Which is good since currently there is a restriction of 1/sec API call. 
```
<meta content="Growing a Revolution" property="og:title">
```
We should definitely do this to reduce API calls. But does this increase network traffic? We still have to reload the website, right? Does HTML allow to only get the Head information?

**Comment by daniel-j-h** [comment]
We do this by now!
